### ISSUE TITLE
rqa in nonlinearTseries version 0.2.12 in RStudio

### ISSUE THREAD

**Issue by domvicinanza** [constantino-garcia/nonlinearTseries#7]
I am trying to run a simple rqa using nonlinearTseries in R using version 0.2.12 of the library

a <- c(1,2,1,2,1,2)
a.rqa <- rqa(time.series = a, embedding.dim = 1, time.lag = 1, radius = .1)

While I never had any issue with this in the past, I noticed that since I upgraded the library to 0.2.12 I have an error:

Error in validObject(r) : 
  invalid class “nsTMatrix” object: uplo="U" but there are entries below the diagonal

I know other colleagues are having the same issue

I also tried removing the library and downgrading it to 0.2.5 (the one that worked), but the C++ compiler (‘Apple clang version 14.0.0 (clang-1400.0.29.102)’) returns the following error:

require(remotes)
install_version("nonlinearTseries", dependencies = TRUE, version = "0.2.5", repos = "https://cran.ma.imperial.ac.uk/")

....

clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I. -IANN -DRANN -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c neighbour_search_wrapper.cpp -o neighbour_search_wrapper.o
neighbour_search_wrapper.cpp:8:25: error: no member named 'bind2nd' in namespace 'std'
                   std::bind2nd(std::plus<int>(), 1));  
                   ~~~~~^
1 error generated.
make: *** [neighbour_search_wrapper.o] Error 1
ERROR: compilation failed for package ‘nonlinearTseries’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/nonlinearTseries’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/0z/nw3d1p6x2c78rd6pg3rlh5dr0000gn/T//RtmpoLcdh3/remotes4a603cc634c1/nonlinearTseries’ had non-zero exit status

Any idea how to either fix the error in the current version or help me reinstall the old one?

Thanks!

**Comment by constantino-garcia** [comment]
At the moment, the issue should be fixed by installing the RQA branch:

devtools::install_github("constantino-garcia/nonlinearTseries", ref ="rqa")

**Comment by domvicinanza** [comment]
Hi Constantino,

Many thanks, it works for me.
Just FYI (in case other people reach out), the way I managed to have it
working is
- installing gcc via homebrew on mac
- create a ~/.R/Makevars file, with the following content

FC = /opt/homebrew/Cellar/gcc/13.2.0/bin/gfortran

F77 = /opt/homebrew/Cellar/gcc/13.2.0/bin/gfortran

FLIBS = -L/opt/homebrew/Cellar/gcc/13.0.0/lib/gcc/13


- restart R and run the installation.



Thanks,

Dom

**Comment by constantino-garcia** [comment]
Great! Thank you very much!

Closing now.
